namespace: "infinidat"
name: "infinibox"
version: "1.4.3"
readme: "README.md"
authors:
  - "Infinidat <partners.infi@infinidat.com>"
  - "David Ohlemacher"
  - "Gregory Shulov"
description: "A set of Ansible modules that allow simple, but powerful, idempotent interactions with Infinidat Infiniboxes."
license:
  - "GPL-3.0-or-later"
tags:
  - array
  - cloud
  - fiber
  - fibre_channel
  - fibrechannel
  - hostpowertools
  - ibox
  - infinibox
  - infinidat
  - infinihost
  - infinisdk
  - iscsi
  - nas
  - nfs
  - san
  - storage
  - storage_array
  - storagearray
repository: "https://www.github.com/infinidat/ansible-infinidat-collection"
issues: "https://www.github.com/infinidat/ansible-infinidat-collection/issues"
build_ignore:
  - '*.sh'
  - '*.swo'
  - '*.swp'
  - '*.tar.gz'
  - '*.un~'
  - '*.pem'
  - '*.csr'
  - '.ropeproject'
  - '.pytest_cache'
  - 'Makefile*'
  - 'collections'
  - 'venv/'
  - 'Session.vim'
  - 'ibox_vars/iboxCICD.yml'
  - 'vault_password.txt'
  - 'scripts/'
  - 'plugins/modules/infini_infinimetrics.py'
