namespace: "infinidat"
name: "infinibox"
version: "1.3.4"
readme: "README.md"
authors:
  - "Infinidat <partners.infi@infinidat.com>"
  - "David Ohlemacher"
  - "Gregory Shulov"
description: "A set of Ansible modules that allow simple, but powerful, idempotent interactions with Infinidat InfiniBoxes."
license:
  - "GPL-3.0-or-later"
tags:
  - cloud
  - fiber
  - fiber_channel
  - fiberchannel
  - hostpowertools
  - ibox
  - infinibox
  - infinidat
  - infinihost
  - infinisdk
  - iscsi
  - nas
  - nfs
  - san
  - storage 
  - storage_array
  - storagearray
repository: "https://www.github.com/infinidat/ansible-infinidat-collection"
issues: "https://www.github.com/infinidat/ansible-infinidat-collection/issues"
build_ignore:  # Supported by ansible 2.10 or newer. Earlier versions generate a warning.
  - '*.sh'
  - '*.swo'
  - '*.swp'
  - '*.tar.gz'
  - '*.un~'
  - '*.un~'
  - './collections'
  - './venv'
  - 'Session.vim'
  - 'ibox_vars/iboxCICD.yml'
