---
- hosts: localhost
  gather_facts: False
  collections:
    - infinidat.infinibox
  vars:
    network_space: InfiniSafe-Fenced-Network # iSCSI
    service: ISCSI_SERVICE
    pool: infinisafe
    volume: app_vol
    snap: app_snap
    lock_time: minutes=3
  tasks:

  - name: Remove snapshot {{ snap }}
    infini_vol:
      name: "{{ snap }}"
      state: absent

      user: "{{ user }}"
      password: "{{ password }}"
      system: "{{ system }}"

  - name: Remove volume {{ volume }} under pool {{ pool }}
    infini_vol:
      name: "{{ volume }}"
      pool: "{{ pool }}"
      state: absent

      user: "{{ user }}"
      password: "{{ password }}"
      system: "{{ system }}"

  - name: Remove pool {{ pool }}
    infini_pool:
      name: "{{ pool }}"
      state: absent

      user: "{{ user }}"
      password: "{{ password }}"
      system: "{{ system }}"

  - name: Remove network space named {{ network_space }}
    infini_network_space:
      name: "{{ network_space }}"
      state: absent

      user: "{{ user }}"
      password: "{{ password }}"
      system: "{{ system }}"


