---
### Localhost
- hosts: localhost
  gather_facts: False
  collections:
    - infinidat.infinibox
  vars:
    network_space: InfiniSafe-Fenced-Network # iSCSI
    service: ISCSI_SERVICE
    pool: infinisafe
    volume: app_vol
    snap: app_snap
    host: forensic-validation-host
    host_iqn: iqn.1993-08.org.debian:01:62ebda3b76cc # io-wt-35
    ibox_portal: 172.31.32.145
    ibox: ibox1521
    ibox_iqn: iqn.2009-11.com.infinidat:storage:infinibox-sn-1521
  tasks:
    
  - name: Create forensic host {{ host }}
    infini_host:
      name: "{{ host }}"
      state: present

      user: "{{ user }}"
      password: "{{ password }}"
      system: "{{ system }}"

  - name: Map snapshot {{ snap }} to host {{ host }}
    infini_map:
      host: "{{ host }}"
      volume: "{{ snap }}"
      state: present

      user: "{{ user }}"
      password: "{{ password }}"
      system: "{{ system }}"

  - name: Add port to host {{ host }}
    infini_port:
      host: "{{ host }}"
      iqns: "{{ host_iqn }}"
      state: present

      user: "{{ user }}"
      password: "{{ password }}"
      system: "{{ system }}"

### Forensics Host
- hosts: forensics
  gather_facts: False
  collections:
    - infinidat.infinibox
  vars:
    network_space: InfiniSafe-Fenced-Network # iSCSI
    service: ISCSI_SERVICE
    pool: infinisafe
    volume: app_vol
    snap: app_snap
    host: forensic-validation-host
    host_iqn: iqn.1993-08.org.debian:01:62ebda3b76cc # io-wt-35
    ibox_portal: 172.31.32.145
    ibox: ibox1521
    ibox_iqn: iqn.2009-11.com.infinidat:storage:infinibox-sn-1521
  tasks:

  - name: Connect forensics host {{ host }} to Infinibox {{ ibox }}
    shell: |
      infinihost iscsi connect {{ ibox }} --netspace={{ network_space }} --hostname={{ host }}
    become: yes

  - name: Connect forensics host {{ host }} to Infinibox {{ ibox }}
    shell: |
      iscsiadm --mode discoverydb --type sendtargets --portal {{ ibox_portal }} --discover
      iscsiadm --mode node --targetname={{ ibox_iqn }} --op update --name=node.session.auth.username --value={{ user }}
      iscsiadm --mode discovery --type sendtargets --portal {{ ibox_portal }} --op show
      iscsiadm --mode node --targetname {{ ibox_iqn }} --portal {{ ibox_portal }} --login
      rescan-scsi-bus.sh
    become: yes

  # Run forensic tests on snapshot {{ snap }}
  - name: Forensically test snapshot {{ snap }} is clean using host {{ host }}
    shell: |
      true
    register: is_snapshot_clean

### Localhost
- hosts: localhost
  gather_facts: False
  collections:
    - infinidat.infinibox
  vars:
    network_space: InfiniSafe-Fenced-Network # iSCSI
    service: ISCSI_SERVICE
    pool: infinisafe
    volume: app_vol
    snap: app_snap
    host: forensic-validation-host
    host_iqn: iqn.1993-08.org.debian:01:62ebda3b76cc # io-wt-35
    ibox_portal: 172.31.32.145
    ibox: ibox1521
    ibox_iqn: iqn.2009-11.com.infinidat:storage:infinibox-sn-1521
  tasks:

  - debug:
      msg: Snapshot {{ snap }} PASSED testing
    when: is_snapshot_clean.rc == 0

  - debug:
      msg: Snapshot {{ snap }} FAILED testing. Do not use this snapshot.
    when: is_snapshot_clean.rc != 0

  - name: Restoring volume {{ volume }} from known clean snapshot {{ snap }}
    infini_vol:
      name: "{{ snap }}"
      state: present
      parent_volume_name: "{{ volume }}"
      volume_type: snapshot
      restore_volume_from_snapshot: True

      user: "{{ user }}"
      password: "{{ password }}"
      system: "{{ system }}"
    when: is_snapshot_clean.rc == 0
