---
# See PSDEV-1000: Fix infini_vols handling of write_protected parameter
# Remove three volumes: vol_nonwriteable, vol_explicitly_writable and vol_writable.
- hosts: localhost
  gather_facts: false
  collections:
    - infinidat.infinibox
  tasks:

    - name: POSITIVE test -> Remove write protected volume {{ auto_prefix }}vol_nonwriteable under pool {{ auto_prefix }}pool
      infini_vol:
        name: "{{ auto_prefix }}vol_nonwriteable"
        pool: "{{ auto_prefix }}pool"
        state: absent
        user: "{{ user }}"
        password: "{{ password }}"
        system: "{{ system }}"

    - name: POSITIVE test -> Remove explicitly writable volume {{ auto_prefix }}vol_explicitly_writable under pool {{ auto_prefix }}pool
      infini_vol:
        name: "{{ auto_prefix }}vol_explicitly_writable"
        pool: "{{ auto_prefix }}pool"
        state: absent
        user: "{{ user }}"
        password: "{{ password }}"
        system: "{{ system }}"

    - name: POSITIVE test -> Remove implicitly writable volume {{ auto_prefix }}vol_writable under pool {{ auto_prefix }}pool
      infini_vol:
        name: "{{ auto_prefix }}vol_writable"
        pool: "{{ auto_prefix }}pool"
        state: absent
        user: "{{ user }}"
        password: "{{ password }}"
        system: "{{ system }}"
