---
# PSDEV-1108: Playbook for testing creation of metadata resources.
- hosts: localhost
  gather_facts: false  # Required for ansible_date_time
  collections:
    - infinidat.infinibox

  vars:
    default_provisioning_body:
      ui-dataset-default-provisioning: "THIN"
    max_number_of_rows_to_export_body:
      ui-table-export-limit: 3001
    dataset_capacity_unit_base10: "false"
    ssd_cache_default: "true"
    compression_enabled_default: "true"
  tasks:

    - name: test set default provisioning to thin
      uri:
        url: "https://{{ system }}/api/rest/metadata/system"
        method: PUT
        user: "{{ user }}"
        password: "{{ password }}"
        force_basic_auth: yes
        status_code: 200,404
        timeout: 10
        validate_certs: false
        body_format: "json"
        body: "{{ default_provisioning_body | to_json }}"
      register: request_api
    - name: debug
      debug:
        var: request_api

    - name: Set dataset capacity unit
      uri:
        url: "https://{{ system }}/api/rest/config/mgmt/mgmt.is_decimal_capacity_converter"
        method: PUT
        user: "{{ user }}"
        password: "{{ password }}"
        force_basic_auth: yes
        status_code: 200,404
        timeout: 10
        validate_certs: false
        body_format: json
        body: "{{ dataset_capacity_unit_base10 }}"
      register: request_api
    - name: debug
      debug:
        var: request_api

    - name: Set pool compression default
      uri:
        url: "https://{{ system }}/api/rest/config/mgmt/pool.compression_enabled_default"
        method: PUT
        user: "{{ user }}"
        password: "{{ password }}"
        force_basic_auth: yes
        status_code: 200,404
        timeout: 10
        validate_certs: false
        body_format: json
        body: "{{ compression_enabled_default }}"
      register: request_api
    - name: debug
      debug:
        var: request_api


    - name: Set SSD Cache default
      uri:
        url: "https://{{ system }}/api/rest/config/mgmt/pool.ssd_enabled_default"
        method: PUT
        user: "{{ user }}"
        password: "{{ password }}"
        force_basic_auth: yes
        status_code: 200,404
        timeout: 10
        validate_certs: false
        body_format: json
        body: "{{ ssd_cache_default }}"
      register: request_api
    - name: debug
      debug:
        var: request_api


    - name: set max number of rows to export
      uri:
        url: "https://{{ system }}/api/rest/metadata/system"
        method: PUT
        user: "{{ user }}"
        password: "{{ password }}"
        force_basic_auth: yes
        status_code: 200,404
        timeout: 10
        validate_certs: false
        body_format: "json"
        body: "{{ max_number_of_rows_to_export_body | to_json }}"
      register: request_api
    - name: debug
      debug:
        var: request_api

    # - name: Check pool compression default
    #   uri:
    #     url: "https://{{ system }}/api/rest/config/mgmt/pool.compression_enabled_default"
    #     method: GET
    #     user: "{{ user }}"
    #     password: "{{ password }}"
    #     force_basic_auth: yes
    #     status_code: 200,404
    #     timeout: 10
    #     validate_certs: false
    #   register: request_api
    # - name: debug
    #   debug:
    #     var: request_api
