---
- hosts: localhost
  gather_facts: false
  vars:
    name: iSCSI
    service: iSCSI
  tasks:

    - name: POSITIVE test -> Remove network space
      infinidat.infinibox.infini_network_space:
        name: "{{ name }}"
        state: absent

        user: "{{ user }}"
        password: "{{ password }}"
        system: "{{ system }}"
