---
# PSDEV-1108: Playbook for testing creation of metadata resources.
- hosts: localhost
  gather_facts: false  # Required for ansible_date_time
  collections:
    - infinidat.infinibox
  tasks:

    # Test any object_type

    - name: Set compression setting to true
      infini_config:
        config_group: "mgmt"
        key: "pool.compression_enabled_default"
        value: false
        state: "present"
        user: "{{ user }}"
        password: "{{ password }}"
        system: "{{ system }}"
      register: metadata_out
    - name: debug
      debug:
        var: metadata_out

    - name: Check current compression setting
      infini_config:
        config_group: "mgmt"
        key: "pool.compression_enabled_default"
        state: "stat"
        user: "{{ user }}"
        password: "{{ password }}"
        system: "{{ system }}"
      register: metadata_out
    - name: debug
      debug:
        var: metadata_out


    - name: Check 2 base
      infini_config:
        config_group: "mgmt"
        key: "mgmt.is_decimal_capacity_converter" # True for Base 10, False for Base 2
        state: "stat"
        user: "{{ user }}"
        password: "{{ password }}"
        system: "{{ system }}"
      register: metadata_out
    - name: debug
      debug:
        var: metadata_out

    - name: Set Dataset capacity unit to Base 2
      infini_config:
        config_group: "mgmt"
        key: "mgmt.is_decimal_capacity_converter" # True for Base 10, False for Base 2
        value: False
        state: "present"
        user: "{{ user }}"
        password: "{{ password }}"
        system: "{{ system }}"
      register: metadata_out
    - name: debug
      debug:
        var: metadata_out
