---
# See PSDEV-1000: Fix infini_vols handling of write_protected parameter
# Create three volumes: vol_nonwriteable, vol_explicitly_writable and vol_writable.
- hosts: localhost
  gather_facts: true  # Required for ansible_date_time
  collections:
    - infinidat.infinibox
  tasks:

    - name: POSITIVE test -> Create pool {{ auto_prefix }}pool
      infini_pool:
        name: "{{ auto_prefix }}pool"
        size: 1TB
        vsize: 1TB
        state: present
        user: "{{ user }}"
        password: "{{ password }}"
        system: "{{ system }}"

    - name: POSITIVE test -> Create write protected volume {{ auto_prefix }}vol_nonwriteable under pool {{ auto_prefix }}pool
      infini_vol:
        name: "{{ auto_prefix }}vol_nonwriteable"
        size: 1GB
        write_protected: true
        pool: "{{ auto_prefix }}pool"
        state: present
        user: "{{ user }}"
        password: "{{ password }}"
        system: "{{ system }}"

    - name: POSITIVE test -> Create explicitly writable {{ auto_prefix }}vol_explicitly_writable under pool {{ auto_prefix }}pool
      infini_vol:
        name: "{{ auto_prefix }}vol_explicitly_writable"
        size: 1GB
        write_protected: false
        pool: "{{ auto_prefix }}pool"
        thin_provision: false
        write_protected: false
        state: present
        user: "{{ user }}"
        password: "{{ password }}"
        system: "{{ system }}"

    - name: POSITIVE test -> Create implicitly writable {{ auto_prefix }}vol_writable under pool {{ auto_prefix }}pool
      infini_vol:
        name: "{{ auto_prefix }}vol_writable"
        size: 1GB
        pool: "{{ auto_prefix }}pool"
        thin_provision: false
        state: present
        user: "{{ user }}"
        password: "{{ password }}"
        system: "{{ system }}"

    - name: POSITIVE test -> Stat nonwritable volume {{ auto_prefix }}vol_nonwriteable under pool {{ auto_prefix }}pool
      register: output
      infini_vol:
        name: "{{ auto_prefix }}vol_nonwriteable"
        pool: "{{ auto_prefix }}pool"
        state: stat
        user: "{{ user }}"
        password: "{{ password }}"
        system: "{{ system }}"
      register: stat_nonwritable

    - debug:
        msg: stat - {{ stat_nonwritable }}

    - name: POSITIVE test -> Stat explicitely writable volume {{ auto_prefix }}vol_explicitly_writable under pool {{ auto_prefix }}pool
      register: output
      infini_vol:
        name: "{{ auto_prefix }}vol_explicitly_writable"
        pool: "{{ auto_prefix }}pool"
        state: stat
        user: "{{ user }}"
        password: "{{ password }}"
        system: "{{ system }}"
      register: stat_explicitely_writable

    - debug:
        msg: stat - {{ stat_explicitely_writable }}

    - name: POSITIVE test -> Stat implicitely writable volume {{ auto_prefix }}vol_writable under pool {{ auto_prefix }}pool
      register: output
      infini_vol:
        name: "{{ auto_prefix }}vol_writable"
        pool: "{{ auto_prefix }}pool"
        state: stat
        user: "{{ user }}"
        password: "{{ password }}"
        system: "{{ system }}"
      register: stat_writable

    - debug:
        msg: stat - {{ stat_writable }}
